version: "3.8"

services:
  rinha:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - payment-processor
    expose:
      - "4444"

  rinha-2:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - payment-processor
    expose:
      - "4444"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    networks:
      - payment-processor
    depends_on:
      - rinha
      - rinha-2

  redis:
    image: redis:alpine3.21
    ports:
      - 6379:6379
    networks:
      - payment-processor

networks:
  payment-processor:
    external: true
