x-service-templates:
  rinha: &rinha
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - payment-processor
    expose:
      - "4444"
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "250mb"
    depends_on:
    - redis
  
services:
  rinha-1:
   <<: *rinha
   environment:
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080

  rinha-2:
   <<: *rinha
   
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:80"
    networks:
      - payment-processor
    depends_on:
      - rinha-1
      - rinha-2

  redis:
    image: redis:alpine3.21
    ports:
      - 6379:6379
    networks:
      - payment-processor

networks:
  payment-processor:
    external: true
